### ISSUE TITLE
Genetic map column names

### ISSUE THREAD

**Issue by lemieuxl** [pgxcentre/region-plot#1]
Since we don't provide a genetic map file with the tool, it would be important to add options to specify the names of the required columns.
- `--genetic-chr-col` for chromosome
- `--genetic-pos-col` for position
- `--genetic-rate-col` for the recombination rate

**Comment by dmitryprok** [comment]
Hi, I downloaded this tool and realized that some of the column names in genetic map file are still hard coded. Also I have added a line to make the code work without the X11. This is probably not enough for a pull request, so I am posting it here. Hope it is useful.
###################################################

Lines 30-33
+import matplotlib as mpl
+mpl.use('Agg')
 import matplotlib.pyplot as plt


Lines 548-553
+region = data[options.genetic_chr_col] == chrom
+region = region & (data[options.genetic_pos_col] >= start)
+region = region & (data[options.genetic_pos_col] <= stop)
     data = data[region]

**Comment by lemieuxl** [comment]
Thanks @dmitryprok. I forgot to change those three lines when I made the fix.
For the *Agg* backend, I did not include the fix, as it is easily performed using the *matplotlibrc* file (`~/.config/matplotlib/matplotlibrc` on my system).

```text
backend: Agg
```
