### ISSUE TITLE
hi，thanks for your tools, how can i kown all parameters' format?

### ISSUE THREAD

**Issue by wuzhaji** [pgxcentre/region-plot#8]

**Comment by lemieuxl** [comment]
The *genotypes* format is one of `vcf`, `impute2`, `plink` or `bgen`. The *assoc* file must be white space delimited. Use the `--help` option to know more about other parameters and options.

**Comment by wuzhaji** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    thank you so much ,can you help me to chick these errors?
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1468849225
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 7/6/2021 20:56，Louis-Philippe Lemieux ***@***.***> wrote： 



The genotypes format is one of vcf, impute2, plink or bgen. The assoc file must be white space delimited. Use the --help option to know more about other parameters and options.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
