### ISSUE TITLE
Could it be somehow usable on other species

### ISSUE THREAD

**Issue by lenkaungrova** [pgxcentre/region-plot#9]
Hi, I really like this script and i was wondering if it can be used also for another species, not just human. What type of build file is needed for checking the overlapping regions? Or is there a way to skip this flag? Thank you very much for your answer. :)

**Comment by lemieuxl** [comment]
The tool uses Ensembl REST API (https://rest.ensembl.org/) to gather genes in a specific region. It would be possible to allow for different species, but not at the current state of the project. Development would be required to allow for any species from Ensembl at their current build (e.g. *mouse* build *GRCm39*).

There is no way at this time to skip this step unless you comment out some part of the code... There would be a way to provide a list of genes in the region, but change to the code would be required to use it.

**Comment by lemieuxl** [comment]
I could probably try and give it a go if you provide an example dataset.

**Comment by lenkaungrova** [comment]
Hi,
thank you for your quick reaction. I can provide a datasets for dog samples. Can I send it by email? :)
